# Generated by Django 3.0.2 on 2020-02-11 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='design_description',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='library_construction_protocol',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='library_layout',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='library_strategy',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sample_accession',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='sample_attribute',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment', to='project.Study'),
        ),
        migrations.AlterField(
            model_name='srr',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='srr', to='project.Experiment'),
        ),
    ]
