# Generated by Django 3.0.2 on 2020-01-27 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.DateTimeField(verbose_name='date published')),
                ('title', models.CharField(max_length=200)),
                ('SampleType', models.CharField(max_length=200)),
                ('SourceName', models.CharField(max_length=200)),
                ('Organizm', models.TextField()),
                ('Characteristics', models.TextField()),
                ('GrowthProtocol', models.TextField()),
                ('ExtractedMolecule', models.CharField(max_length=200)),
                ('ExtractionProtocol', models.TextField()),
                ('LibraryStrategy', models.CharField(max_length=200)),
                ('LibrarySource', models.CharField(max_length=200)),
                ('LibrarySelection', models.CharField(max_length=200)),
                ('InstrumentModel', models.CharField(max_length=200)),
                ('Description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo_accession', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('geo_accession', models.CharField(max_length=200, unique=True)),
                ('experiment_mode', models.TextField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date published')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RiboBase.Study')),
            ],
        ),
    ]
