# Generated by Django 3.0.2 on 2020-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiboBase', '0002_experiment_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_show',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
