# Generated by Django 3.0.2 on 2020-02-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiboBase', '0004_auto_20200205_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='Status',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
