# Generated by Django 3.0.2 on 2020-02-05 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiboBase', '0005_auto_20200205_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='experiment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='RiboBase.Experiment_show'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Experiment',
        ),
    ]
