# Generated by Django 3.0.2 on 2020-02-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiboBase', '0006_auto_20200205_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='experiment',
        ),
        migrations.AddField(
            model_name='metadata',
            name='Experiment_show',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, related_name='MetaData', to='RiboBase.Experiment_show'),
            preserve_default=False,
        ),
    ]
