# Generated by Django 3.0.2 on 2020-02-05 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiboBase', '0008_auto_20200205_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='Experiment_show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MetaData', to='RiboBase.Experiment_show'),
        ),
    ]
