# Generated by Django 3.0.2 on 2020-02-05 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RiboBase', '0014_auto_20200205_2215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='metadata',
            old_name='Experiment_show',
            new_name='experiment',
        ),
    ]
