# Generated by Django 3.0.2 on 2020-02-07 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiboBase', '0015_auto_20200205_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment_show',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Study_num', to='RiboBase.Study'),
        ),
    ]
