# Generated by Django 3.0.2 on 2020-02-07 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RiboBase', '0016_auto_20200207_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment_show',
            name='study',
        ),
        migrations.AlterField(
            model_name='experiment_show',
            name='Geo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Study_num', to='RiboBase.Study'),
        ),
    ]
