# Generated by Django 3.0.2 on 2020-02-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RiboBase', '0017_auto_20200207_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='geo_accession',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
